"""
Phasics — Adaptive Question Bank
Wave Mechanics: SHM & Standing Waves
"""

QUESTION_BANK = [
    # ═══════════════════════════════════════
    # LEVEL 1 — Foundational
    # ═══════════════════════════════════════
    {
        "id": "shm-1",
        "topic": "SHM",
        "subtopic": "Definitions",
        "level": 1,
        "type": "multiple_choice",
        "question": "For a mass-spring system undergoing SHM, the restoring force is F = −kx. Which statement correctly describes the phase relationship between displacement x(t) and acceleration a(t)?",
        "options": [
            "a(t) leads x(t) by π/2 radians",
            "a(t) and x(t) are exactly in phase",
            "a(t) and x(t) are exactly π radians out of phase (anti-phase)",
            "a(t) lags x(t) by π/2 radians",
        ],
        "correct": 2,
        "explanation": "Since a = −ω²x, acceleration is always proportional to displacement but opposite in sign. If x = A cos(ωt), then a = −Aω² cos(ωt). The negative sign means they are π radians (180°) out of phase — when displacement is maximum positive, acceleration is maximum negative.",
    },
    {
        "id": "shm-2",
        "topic": "SHM",
        "subtopic": "Period & Frequency",
        "level": 1,
        "type": "numerical",
        "question": "A simple pendulum has a period of 2.00 s on Earth (g = 9.81 m/s²). What is the length of the pendulum in meters?",
        "correct": 0.994,
        "tolerance": 0.02,
        "unit": "m",
        "explanation": "T = 2π√(L/g) → L = gT²/(4π²) = (9.81)(2.00)²/(4π²) = 39.24/39.48 ≈ 0.994 m. The period of a simple pendulum is independent of mass and amplitude (for small angles).",
    },
    {
        "id": "shm-3",
        "topic": "SHM",
        "subtopic": "Energy",
        "level": 1,
        "type": "multiple_choice",
        "question": "In SHM, at what displacement from equilibrium is the kinetic energy equal to the potential energy?",
        "options": [
            "x = A/2",
            "x = A/√2",
            "x = A/4",
            "x = A√2",
        ],
        "correct": 1,
        "explanation": "Total energy E = ½kA². At displacement x: PE = ½kx², KE = E − PE = ½k(A² − x²). Setting KE = PE: ½kx² = ½k(A² − x²) → 2x² = A² → x = A/√2 ≈ 0.707A.",
    },
    # ═══════════════════════════════════════
    # LEVEL 2 — Developing
    # ═══════════════════════════════════════
    {
        "id": "shm-4",
        "topic": "SHM",
        "subtopic": "Equations of Motion",
        "level": 2,
        "type": "numerical",
        "question": "A 0.250 kg mass oscillates on a spring with k = 100 N/m and amplitude 0.08 m. Calculate the magnitude of the maximum acceleration in m/s².",
        "correct": 32.0,
        "tolerance": 0.5,
        "unit": "m/s²",
        "explanation": "Maximum acceleration occurs at maximum displacement: |a_max| = ω²A = (k/m)A = (100/0.250)(0.08) = 400 × 0.08 = 32.0 m/s².",
    },
    {
        "id": "shm-5",
        "topic": "SHM",
        "subtopic": "Equations of Motion",
        "level": 2,
        "type": "multiple_choice",
        "question": "A particle undergoes SHM with x(t) = 0.12 sin(5πt + π/4) in SI units. What is the particle's velocity at t = 0?",
        "options": [
            "0.60π cos(π/4) ≈ 1.33 m/s",
            "0.12 cos(π/4) ≈ 0.085 m/s",
            "0.60π sin(π/4) ≈ 1.33 m/s",
            "−0.60π cos(π/4) ≈ −1.33 m/s",
        ],
        "correct": 0,
        "explanation": "v(t) = dx/dt = 0.12(5π)cos(5πt + π/4) = 0.60π cos(5πt + π/4). At t = 0: v(0) = 0.60π cos(π/4) = 0.60π(√2/2) ≈ 1.33 m/s.",
    },
    {
        "id": "shm-6",
        "topic": "SHM",
        "subtopic": "Energy",
        "level": 2,
        "type": "numerical",
        "question": "Two identical springs (k = 300 N/m each) are connected in parallel to a 1.5 kg block. The block is displaced 0.10 m and released. What is the total mechanical energy of the system in joules?",
        "correct": 3.0,
        "tolerance": 0.05,
        "unit": "J",
        "explanation": "Springs in parallel: k_eff = k₁ + k₂ = 300 + 300 = 600 N/m. Total energy E = ½k_eff·A² = ½(600)(0.10)² = 3.0 J.",
    },
    # ═══════════════════════════════════════
    # LEVEL 3 — Proficient
    # ═══════════════════════════════════════
    {
        "id": "sw-1",
        "topic": "Standing Waves",
        "subtopic": "Harmonics",
        "level": 3,
        "type": "multiple_choice",
        "question": "A string of length L is fixed at both ends. If the tension is quadrupled while mass per unit length remains constant, what happens to the fundamental frequency?",
        "options": [
            "It doubles",
            "It quadruples",
            "It increases by a factor of √2",
            "It halves",
        ],
        "correct": 0,
        "explanation": "f₁ = (1/2L)√(T/μ). If T → 4T: f₁' = (1/2L)√(4T/μ) = 2 × (1/2L)√(T/μ) = 2f₁. The fundamental frequency doubles because wave speed v = √(T/μ) doubles.",
    },
    {
        "id": "sw-2",
        "topic": "Standing Waves",
        "subtopic": "Wave Speed",
        "level": 3,
        "type": "numerical",
        "question": "A 1.20 m long steel wire has a mass of 9.60 × 10⁻³ kg and is under 120 N tension. Calculate the frequency of the 3rd harmonic in Hz.",
        "correct": 153.0,
        "tolerance": 2,
        "unit": "Hz",
        "explanation": "μ = m/L = 9.60×10⁻³/1.20 = 8.00×10⁻³ kg/m. v = √(T/μ) = √(120/8.00×10⁻³) = √15000 ≈ 122.5 m/s. f₃ = 3v/(2L) = 3(122.5)/(2×1.20) ≈ 153 Hz.",
    },
    {
        "id": "sw-3",
        "topic": "Standing Waves",
        "subtopic": "Resonance",
        "level": 3,
        "type": "multiple_choice",
        "question": "An organ pipe open at both ends has a fundamental frequency of 440 Hz. If one end is now closed, what is the new fundamental frequency?",
        "options": [
            "440 Hz",
            "220 Hz",
            "880 Hz",
            "110 Hz",
        ],
        "correct": 1,
        "explanation": "Open pipe fundamental: f = v/(2L) = 440 Hz. Closed pipe fundamental: f' = v/(4L) = ½ × v/(2L) = 220 Hz. Closing one end doubles the effective wavelength of the fundamental (λ = 2L → λ = 4L), halving the frequency.",
    },
    {
        "id": "sw-4",
        "topic": "Standing Waves",
        "subtopic": "Superposition",
        "level": 3,
        "type": "conceptual",
        "question": "Two wave pulses of equal amplitude travel toward each other on a string. One is upright and one is inverted. Describe what happens at the instant they completely overlap, and explain whether energy is conserved at that instant.",
        "rubric": ["destructive interference", "zero displacement", "energy is conserved", "kinetic energy", "string has velocity", "energy stored in motion not displacement"],
        "explanation": "At the instant of complete overlap, destructive interference produces zero displacement everywhere. However, energy IS conserved — at that instant, the string has zero potential energy but maximum kinetic energy because every point has nonzero transverse velocity. After passing through each other, the pulses re-emerge unchanged.",
    },
    # ═══════════════════════════════════════
    # LEVEL 4 — Advanced
    # ═══════════════════════════════════════
    {
        "id": "shm-7",
        "topic": "SHM",
        "subtopic": "Damped Oscillations",
        "level": 4,
        "type": "multiple_choice",
        "question": "A damped oscillator loses 5% of its energy per cycle. After how many complete cycles will the energy drop to less than half its initial value?",
        "options": [
            "10 cycles",
            "14 cycles",
            "7 cycles",
            "20 cycles",
        ],
        "correct": 1,
        "explanation": "After n cycles: E_n = E₀(0.95)ⁿ. We need (0.95)ⁿ < 0.5. Taking ln: n > ln(0.5)/ln(0.95) = −0.693/(−0.0513) ≈ 13.51. So n = 14 complete cycles.",
    },
    {
        "id": "sw-5",
        "topic": "Standing Waves",
        "subtopic": "Resonance",
        "level": 4,
        "type": "numerical",
        "question": "A tube closed at one end resonates at consecutive frequencies of 850 Hz and 1190 Hz. What is the fundamental frequency of the tube in Hz?",
        "correct": 170.0,
        "tolerance": 2,
        "unit": "Hz",
        "explanation": "A closed tube has only odd harmonics: fₙ = nf₁ for n = 1, 3, 5, 7... Consecutive resonant frequencies differ by 2f₁. So 2f₁ = 1190 − 850 = 340 Hz → f₁ = 170 Hz. (850 = 5 × 170, 1190 = 7 × 170 ✓)",
    },
    {
        "id": "shm-8",
        "topic": "SHM",
        "subtopic": "Coupled Oscillations",
        "level": 4,
        "type": "conceptual",
        "question": "Two identical pendulums are connected by a weak spring. When one is set into motion while the other is at rest, the energy gradually transfers back and forth between them. Explain why this energy transfer occurs in terms of normal modes.",
        "rubric": ["two normal modes", "symmetric mode", "antisymmetric mode", "slightly different frequencies", "superposition", "beat frequency", "difference in normal mode frequencies"],
        "explanation": "The coupled system has two normal modes: symmetric (both swing in phase, freq ω₁) and antisymmetric (opposite phase, freq ω₂ > ω₁). The initial condition is a superposition of both modes. Because ω₁ ≠ ω₂, the modes go in and out of phase with beat frequency |ω₂ − ω₁|, causing periodic energy transfer.",
    },
    {
        "id": "sw-6",
        "topic": "Standing Waves",
        "subtopic": "Wave Equation",
        "level": 4,
        "type": "multiple_choice",
        "question": "A standing wave is described by y(x,t) = 2A sin(kx)cos(ωt). At a position where sin(kx) = 0.5, what is the ratio of the maximum kinetic energy density to the maximum potential energy density at that point?",
        "options": [
            "1:1",
            "1:4",
            "4:1",
            "It depends on the frequency",
        ],
        "correct": 0,
        "explanation": "At any given point in a standing wave, the oscillation is SHM with local amplitude 2A sin(kx). For SHM, max KE equals max PE (they occur at different times). The ratio is always 1:1 regardless of position.",
    },
    # ═══════════════════════════════════════
    # LEVEL 5 — Expert
    # ═══════════════════════════════════════
    {
        "id": "shm-9",
        "topic": "SHM",
        "subtopic": "Damped Oscillations",
        "level": 5,
        "type": "numerical",
        "question": "A damped oscillator has mass 0.200 kg, spring constant 50.0 N/m, and damping coefficient b = 0.400 kg/s. Calculate the Q-factor (quality factor) of this oscillator.",
        "correct": 7.91,
        "tolerance": 0.15,
        "unit": "",
        "explanation": "Q = √(mk)/b = √(0.200 × 50.0)/0.400 = √10/0.400 = 3.162/0.400 = 7.91. The Q-factor measures how many oscillations occur before significant energy loss.",
    },
    {
        "id": "sw-7",
        "topic": "Standing Waves",
        "subtopic": "Wave Equation",
        "level": 5,
        "type": "conceptual",
        "question": "Derive the condition for resonant frequencies of a string fixed at x = 0 and attached to a massless ring that slides freely on a vertical rod at x = L. How does this differ from the fixed-fixed case and why?",
        "rubric": ["node at x=0", "antinode at x=L", "free end boundary condition", "derivative zero at free end", "L = (2n-1)λ/4 or equivalent", "odd harmonics only", "half the fundamental frequency"],
        "explanation": "At x = 0 (fixed): node. At x = L (free ring): antinode (∂y/∂x = 0). This gives L = (2n−1)λ/4 for n = 1,2,3... So fₙ = (2n−1)v/(4L), yielding only odd harmonics. The fundamental f₁ = v/(4L) is half that of a fixed-fixed string.",
    },
    {
        "id": "shm-10",
        "topic": "SHM",
        "subtopic": "Coupled Oscillations",
        "level": 5,
        "type": "multiple_choice",
        "question": "A mass m hangs from a spring (constant k) inside an elevator. The elevator accelerates upward with acceleration a. Compared to the stationary case, how do the equilibrium extension and oscillation frequency change?",
        "options": [
            "Both equilibrium extension and frequency increase",
            "Equilibrium extension increases; frequency stays the same",
            "Equilibrium extension stays the same; frequency increases",
            "Both stay the same",
        ],
        "correct": 1,
        "explanation": "Effective gravity g_eff = g + a → new equilibrium kx₀ = m(g+a), so x₀ increases. But oscillation about the new equilibrium still has F = −kΔx, so ω = √(k/m) is unchanged. Frequency is independent of gravity.",
    },
    {
        "id": "sw-8",
        "topic": "Standing Waves",
        "subtopic": "Superposition",
        "level": 5,
        "type": "numerical",
        "question": "Two traveling waves y₁ = 3.0 sin(4x − 2t) and y₂ = 3.0 sin(4x + 2t) (SI units) interfere on a string. What is the distance in meters between adjacent nodes?",
        "correct": 0.785,
        "tolerance": 0.015,
        "unit": "m",
        "explanation": "Superposition: y = 6.0 sin(4x)cos(2t). Nodes where sin(4x) = 0 → 4x = nπ → x = nπ/4. Distance between adjacent nodes = π/4 ≈ 0.785 m.",
    },
    # ═══════════════════════════════════════
    # DRAWING QUESTIONS
    # ═══════════════════════════════════════
    {
        "id": "draw-1",
        "topic": "Standing Waves",
        "subtopic": "Harmonics",
        "level": 2,
        "type": "drawing",
        "question": "Sketch the 3rd harmonic standing wave pattern for a string fixed at both ends. Show the nodes (N) and antinodes (A) clearly.",
        "drawing_prompt": "Draw the 3rd harmonic of a string fixed at both ends",
        "eval_criteria": [
            "Shows 3 half-wavelengths fitting in the string length",
            "Has 4 nodes (including the 2 fixed endpoints)",
            "Has 3 antinodes between the nodes",
            "Wave has sinusoidal shape",
            "Amplitude is roughly equal at each antinode",
        ],
        "explanation": "The 3rd harmonic has 3 half-wavelengths (λ/2) fitting in length L, so λ = 2L/3. There are 4 nodes (n+1 = 3+1) including both fixed endpoints, and 3 antinodes midway between each pair of nodes.",
    },
    {
        "id": "draw-2",
        "topic": "SHM",
        "subtopic": "Energy",
        "level": 3,
        "type": "drawing",
        "question": "Sketch a graph showing how kinetic energy (KE) and potential energy (PE) vary with displacement x for a mass-spring system in SHM. The x-axis should go from −A to +A.",
        "drawing_prompt": "Draw KE and PE vs displacement for SHM (x-axis: -A to +A)",
        "eval_criteria": [
            "PE curve is a parabola (U-shape) centered at x=0",
            "PE is zero at x=0 and maximum at x=±A",
            "KE curve is an inverted parabola",
            "KE is maximum at x=0 and zero at x=±A",
            "KE and PE curves intersect at x = ±A/√2",
            "Total energy line is constant/horizontal",
        ],
        "explanation": "PE = ½kx² is a parabola with minimum at equilibrium. KE = ½k(A²−x²) is an inverted parabola. They intersect at x = ±A/√2 where KE = PE. The total energy E = KE + PE = ½kA² is constant.",
    },
    {
        "id": "draw-3",
        "topic": "Standing Waves",
        "subtopic": "Resonance",
        "level": 3,
        "type": "drawing",
        "question": "Sketch the displacement patterns for the 1st and 3rd harmonics of a pipe CLOSED at the left end and OPEN at the right end. Label the nodes (N) and antinodes (A).",
        "drawing_prompt": "Draw 1st and 3rd harmonics of a closed-open pipe",
        "eval_criteria": [
            "Node at the closed (left) end for both harmonics",
            "Antinode at the open (right) end for both harmonics",
            "1st harmonic shows quarter wavelength (λ/4) fitting in the pipe",
            "3rd harmonic shows three-quarter wavelength (3λ/4) fitting in the pipe",
            "Sinusoidal wave shapes",
        ],
        "explanation": "A closed-open pipe has a node at the closed end and antinode at the open end. The 1st harmonic fits λ/4 in length L (f₁ = v/4L). The 3rd harmonic fits 3λ/4 (f₃ = 3v/4L). Only odd harmonics are supported.",
    },
    {
        "id": "draw-4",
        "topic": "Standing Waves",
        "subtopic": "Superposition",
        "level": 4,
        "type": "drawing",
        "question": "Two identical wave pulses approach each other from opposite ends of a string. The left pulse is upright (positive) and the right pulse is inverted (negative). Sketch three frames: (1) before overlap, (2) at complete overlap, (3) after they pass through each other.",
        "drawing_prompt": "Draw 3 frames of two opposite pulses passing through each other",
        "eval_criteria": [
            "Frame 1: two separate pulses approaching (one up, one down)",
            "Frame 2: complete destructive interference showing flat/zero displacement",
            "Frame 3: pulses have passed through each other and continue in original directions",
            "Pulses maintain their shape after passing through each other",
        ],
        "explanation": "When the two opposite pulses completely overlap, destructive interference produces zero displacement everywhere. But the pulses pass through each other and re-emerge with their original shapes — waves don't bounce off each other, they superpose and continue.",
    },
    # ═══════════════════════════════════════
    # MATH INPUT QUESTIONS
    # ═══════════════════════════════════════
    {
        "id": "math-1",
        "topic": "SHM",
        "subtopic": "Equations of Motion",
        "level": 3,
        "type": "math_input",
        "question": "A mass-spring system has m = 0.5 kg, k = 200 N/m, amplitude A = 0.1 m, and starts at maximum displacement. Write the complete equation for position x(t) in terms of the given values (use cos or sin notation).",
        "expected_form": "x(t) = 0.1 cos(20t)",
        "eval_keywords": ["0.1", "cos", "20"],
        "eval_criteria": [
            "Amplitude is 0.1 m",
            "Angular frequency ω = √(k/m) = √(200/0.5) = 20 rad/s",
            "Uses cosine (starts at max displacement)",
            "Correct form: x(t) = 0.1 cos(20t)",
        ],
        "explanation": "Since the mass starts at maximum displacement, we use cosine: x(t) = A cos(ωt). With ω = √(k/m) = √(200/0.5) = √400 = 20 rad/s, the equation is x(t) = 0.1 cos(20t).",
    },
    {
        "id": "math-2",
        "topic": "SHM",
        "subtopic": "Equations of Motion",
        "level": 4,
        "type": "math_input",
        "question": "Starting from x(t) = A cos(ωt + φ), derive the expression for the velocity v(t) and the acceleration a(t). Write both expressions.",
        "expected_form": "v(t) = -Aω sin(ωt + φ), a(t) = -Aω² cos(ωt + φ)",
        "eval_keywords": ["-A", "omega", "sin", "omega^2", "cos", "derivative"],
        "eval_criteria": [
            "v(t) is the first derivative of x(t)",
            "v(t) = -Aω sin(ωt + φ)",
            "a(t) is the second derivative of x(t)",
            "a(t) = -Aω² cos(ωt + φ)",
            "Negative signs are correct",
        ],
        "explanation": "Taking derivatives: v(t) = dx/dt = -Aω sin(ωt + φ). Then a(t) = dv/dt = -Aω² cos(ωt + φ). Notice that a(t) = -ω²x(t), confirming the defining property of SHM.",
    },
    {
        "id": "math-3",
        "topic": "Standing Waves",
        "subtopic": "Wave Equation",
        "level": 5,
        "type": "math_input",
        "question": "Write the general expression for the resonant frequencies fₙ of a string of length L, tension T, and linear mass density μ, fixed at both ends. Then write the expression for a pipe of the same length closed at one end and open at the other (speed of sound = v).",
        "expected_form": "String: fₙ = n/(2L) √(T/μ) for n=1,2,3... | Pipe: fₙ = nv/(4L) for n=1,3,5...",
        "eval_keywords": ["n", "2L", "T", "mu", "4L", "odd"],
        "eval_criteria": [
            "String: fₙ = n√(T/μ)/(2L) or equivalent",
            "String harmonics: n = 1, 2, 3... (all integers)",
            "Pipe: fₙ = nv/(4L)",
            "Pipe harmonics: n = 1, 3, 5... (odd integers only)",
        ],
        "explanation": "String fixed at both ends: fₙ = n/(2L)·√(T/μ) for all positive integers n. The wave speed is v = √(T/μ). Closed-open pipe: fₙ = nv/(4L) for odd n only (1, 3, 5...) because only odd harmonics satisfy the boundary conditions (node at closed end, antinode at open end).",
    },
]
