"""
Phasics — Adaptive Question Bank
Wave Mechanics: SHM & Standing Waves
All questions use $...$ for inline LaTeX rendering.
"""

QUESTION_BANK = [
    # ═══════════════════════════════════════
    # LEVEL 1 — Foundational
    # ═══════════════════════════════════════
    {
        "id": "shm-1",
        "topic": "SHM",
        "subtopic": "Definitions",
        "level": 1,
        "type": "multiple_choice",
        "question": "For a mass-spring system undergoing SHM, the restoring force is $F = -kx$. Which statement correctly describes the phase relationship between displacement $x(t)$ and acceleration $a(t)$?",
        "options": [
            "$a(t)$ leads $x(t)$ by $\\frac{\\pi}{2}$ radians",
            "$a(t)$ and $x(t)$ are exactly in phase",
            "$a(t)$ and $x(t)$ are exactly $\\pi$ radians out of phase (anti-phase)",
            "$a(t)$ lags $x(t)$ by $\\frac{\\pi}{2}$ radians",
        ],
        "correct": 2,
        "explanation": "Since $a = -\\omega^2 x$, acceleration is always proportional to displacement but opposite in sign. If $x = A\\cos(\\omega t)$, then $a = -A\\omega^2 \\cos(\\omega t)$. The negative sign means they are $\\pi$ radians (180°) out of phase.",
    },
    {
        "id": "shm-2",
        "topic": "SHM",
        "subtopic": "Period & Frequency",
        "level": 1,
        "type": "numerical",
        "question": "A simple pendulum has a period of $T = 2.00$ s on Earth ($g = 9.81$ m/s²). What is the length of the pendulum in meters?",
        "correct": 0.994,
        "tolerance": 0.02,
        "unit": "m",
        "explanation": "$T = 2\\pi\\sqrt{\\frac{L}{g}} \\implies L = \\frac{gT^2}{4\\pi^2} = \\frac{(9.81)(2.00)^2}{4\\pi^2} \\approx 0.994$ m.",
    },
    {
        "id": "shm-3",
        "topic": "SHM",
        "subtopic": "Energy",
        "level": 1,
        "type": "multiple_choice",
        "question": "In SHM, at what displacement from equilibrium is the kinetic energy equal to the potential energy?",
        "options": [
            "$x = \\frac{A}{2}$",
            "$x = \\frac{A}{\\sqrt{2}}$",
            "$x = \\frac{A}{4}$",
            "$x = A\\sqrt{2}$",
        ],
        "correct": 1,
        "explanation": "Total energy $E = \\frac{1}{2}kA^2$. Setting $\\text{KE} = \\text{PE}$: $\\frac{1}{2}kx^2 = \\frac{1}{2}k(A^2 - x^2) \\implies 2x^2 = A^2 \\implies x = \\frac{A}{\\sqrt{2}}$.",
    },
    # ═══════════════════════════════════════
    # LEVEL 2 — Developing
    # ═══════════════════════════════════════
    {
        "id": "shm-4",
        "topic": "SHM",
        "subtopic": "Equations of Motion",
        "level": 2,
        "type": "numerical",
        "question": "A $0.250$ kg mass oscillates on a spring with $k = 100$ N/m and amplitude $A = 0.08$ m. Calculate $|a_{\\max}|$ in m/s².",
        "correct": 32.0,
        "tolerance": 0.5,
        "unit": "m/s²",
        "explanation": "$|a_{\\max}| = \\omega^2 A = \\frac{k}{m}A = \\frac{100}{0.250}(0.08) = 32.0$ m/s².",
    },
    {
        "id": "shm-5",
        "topic": "SHM",
        "subtopic": "Equations of Motion",
        "level": 2,
        "type": "multiple_choice",
        "question": "A particle undergoes SHM with $x(t) = 0.12\\sin\\!\\left(5\\pi t + \\frac{\\pi}{4}\\right)$ in SI units. What is the velocity at $t = 0$?",
        "options": [
            "$0.60\\pi \\cos\\!\\left(\\frac{\\pi}{4}\\right) \\approx 1.33$ m/s",
            "$0.12 \\cos\\!\\left(\\frac{\\pi}{4}\\right) \\approx 0.085$ m/s",
            "$0.60\\pi \\sin\\!\\left(\\frac{\\pi}{4}\\right) \\approx 1.33$ m/s",
            "$-0.60\\pi \\cos\\!\\left(\\frac{\\pi}{4}\\right) \\approx -1.33$ m/s",
        ],
        "correct": 0,
        "explanation": "$v(t) = 0.60\\pi \\cos(5\\pi t + \\frac{\\pi}{4})$. At $t=0$: $v(0) = 0.60\\pi \\cos(\\frac{\\pi}{4}) \\approx 1.33$ m/s.",
    },
    {
        "id": "shm-6",
        "topic": "SHM",
        "subtopic": "Energy",
        "level": 2,
        "type": "numerical",
        "question": "Two identical springs ($k = 300$ N/m each) are connected in parallel to a $1.5$ kg block displaced $0.10$ m. What is the total energy $E$ in joules?",
        "correct": 3.0,
        "tolerance": 0.05,
        "unit": "J",
        "explanation": "$k_{\\text{eff}} = 600$ N/m. $E = \\frac{1}{2}k_{\\text{eff}} A^2 = \\frac{1}{2}(600)(0.10)^2 = 3.0$ J.",
    },
    # ═══════════════════════════════════════
    # LEVEL 3 — Proficient
    # ═══════════════════════════════════════
    {
        "id": "sw-1",
        "topic": "Standing Waves",
        "subtopic": "Harmonics",
        "level": 3,
        "type": "multiple_choice",
        "question": "A string of length $L$ is fixed at both ends. If the tension $T$ is quadrupled while $\\mu$ stays constant, what happens to $f_1$?",
        "options": [
            "It doubles",
            "It quadruples",
            "It increases by $\\sqrt{2}$",
            "It halves",
        ],
        "correct": 0,
        "explanation": "$f_1 = \\frac{1}{2L}\\sqrt{\\frac{T}{\\mu}}$. If $T \\to 4T$: $f_1' = 2f_1$. The frequency doubles.",
    },
    {
        "id": "sw-2",
        "topic": "Standing Waves",
        "subtopic": "Wave Speed",
        "level": 3,
        "type": "numerical",
        "question": "A $1.20$ m wire ($m = 9.60 \\times 10^{-3}$ kg, $T = 120$ N). Calculate $f_3$ in Hz.",
        "correct": 153.0,
        "tolerance": 2,
        "unit": "Hz",
        "explanation": "$\\mu = 8.00 \\times 10^{-3}$ kg/m. $v = \\sqrt{T/\\mu} \\approx 122.5$ m/s. $f_3 = \\frac{3v}{2L} \\approx 153$ Hz.",
    },
    {
        "id": "sw-3",
        "topic": "Standing Waves",
        "subtopic": "Resonance",
        "level": 3,
        "type": "multiple_choice",
        "question": "An organ pipe open at both ends has $f_1 = 440$ Hz. If one end is closed, what is the new fundamental?",
        "options": ["$440$ Hz", "$220$ Hz", "$880$ Hz", "$110$ Hz"],
        "correct": 1,
        "explanation": "Open: $f = \\frac{v}{2L}$. Closed: $f' = \\frac{v}{4L} = \\frac{1}{2} \\cdot \\frac{v}{2L} = 220$ Hz.",
    },
    {
        "id": "sw-4",
        "topic": "Standing Waves",
        "subtopic": "Superposition",
        "level": 3,
        "type": "conceptual",
        "question": "Two wave pulses of equal amplitude travel toward each other on a string. One is upright, one inverted. Describe what happens at the instant they completely overlap. Is energy conserved at that instant?",
        "rubric": ["destructive interference", "zero displacement", "energy is conserved", "kinetic energy", "string has velocity", "energy stored in motion not displacement"],
        "explanation": "At complete overlap, destructive interference gives zero displacement everywhere. Energy IS conserved — at that instant $\\text{PE} = 0$ but $\\text{KE}$ is maximum (every point has nonzero transverse velocity). After passing through, pulses re-emerge unchanged.",
    },
    # ═══════════════════════════════════════
    # LEVEL 4 — Advanced
    # ═══════════════════════════════════════
    {
        "id": "shm-7",
        "topic": "SHM",
        "subtopic": "Damped Oscillations",
        "level": 4,
        "type": "multiple_choice",
        "question": "A damped oscillator loses $5\\%$ of its energy per cycle. After how many cycles does $E < \\frac{1}{2}E_0$?",
        "options": ["10 cycles", "14 cycles", "7 cycles", "20 cycles"],
        "correct": 1,
        "explanation": "$E_n = E_0(0.95)^n$. Need $(0.95)^n < 0.5 \\implies n > \\frac{\\ln 0.5}{\\ln 0.95} \\approx 13.51$. So $n = 14$.",
    },
    {
        "id": "sw-5",
        "topic": "Standing Waves",
        "subtopic": "Resonance",
        "level": 4,
        "type": "numerical",
        "question": "A closed tube resonates at consecutive frequencies $850$ Hz and $1190$ Hz. Find $f_1$ in Hz.",
        "correct": 170.0,
        "tolerance": 2,
        "unit": "Hz",
        "explanation": "Closed tube: odd harmonics only, consecutive resonances differ by $2f_1$. $2f_1 = 1190 - 850 = 340 \\implies f_1 = 170$ Hz.",
    },
    {
        "id": "shm-8",
        "topic": "SHM",
        "subtopic": "Coupled Oscillations",
        "level": 4,
        "type": "conceptual",
        "question": "Two identical pendulums connected by a weak spring exhibit energy transfer (beats). Explain in terms of normal modes why the energy oscillates between the pendulums.",
        "rubric": ["two normal modes", "symmetric mode", "antisymmetric mode", "slightly different frequencies", "superposition", "beat frequency", "difference in normal mode frequencies"],
        "explanation": "Two normal modes exist: symmetric ($\\omega_1$) and antisymmetric ($\\omega_2 > \\omega_1$). The initial state is a superposition of both. Since $\\omega_1 \\neq \\omega_2$, they go in/out of phase with beat frequency $|\\omega_2 - \\omega_1|$, transferring energy periodically.",
    },
    {
        "id": "sw-6",
        "topic": "Standing Waves",
        "subtopic": "Wave Equation",
        "level": 4,
        "type": "multiple_choice",
        "question": "For $y(x,t) = 2A\\sin(kx)\\cos(\\omega t)$, at a point where $\\sin(kx) = 0.5$, what is $\\text{KE}_{\\max} : \\text{PE}_{\\max}$?",
        "options": ["$1:1$", "$1:4$", "$4:1$", "Depends on $\\omega$"],
        "correct": 0,
        "explanation": "At any point, the oscillation is SHM with local amplitude $2A\\sin(kx)$. For SHM, $\\text{KE}_{\\max} = \\text{PE}_{\\max}$ always. Ratio is $1:1$.",
    },
    # ═══════════════════════════════════════
    # LEVEL 5 — Expert
    # ═══════════════════════════════════════
    {
        "id": "shm-9",
        "topic": "SHM",
        "subtopic": "Damped Oscillations",
        "level": 5,
        "type": "numerical",
        "question": "Damped oscillator: $m = 0.200$ kg, $k = 50.0$ N/m, $b = 0.400$ kg/s. Calculate the quality factor $Q$.",
        "correct": 7.91,
        "tolerance": 0.15,
        "unit": "",
        "explanation": "$Q = \\frac{\\sqrt{mk}}{b} = \\frac{\\sqrt{10}}{0.400} = 7.91$.",
    },
    {
        "id": "sw-7",
        "topic": "Standing Waves",
        "subtopic": "Wave Equation",
        "level": 5,
        "type": "conceptual",
        "question": "Derive the resonant frequency condition for a string fixed at $x = 0$ with a free end (massless ring on rod) at $x = L$. How does $f_1$ compare to the fixed-fixed case?",
        "rubric": ["node at x=0", "antinode at x=L", "free end boundary condition", "derivative zero at free end", "L = (2n-1)λ/4 or equivalent", "odd harmonics only", "half the fundamental frequency"],
        "explanation": "Fixed at $x=0$: node. Free at $x=L$: antinode ($\\partial y/\\partial x = 0$). $L = \\frac{(2n-1)\\lambda}{4}$ so $f_n = \\frac{(2n-1)v}{4L}$, odd harmonics only. $f_1 = \\frac{v}{4L}$, half of fixed-fixed.",
    },
    {
        "id": "shm-10",
        "topic": "SHM",
        "subtopic": "Coupled Oscillations",
        "level": 5,
        "type": "multiple_choice",
        "question": "Mass $m$ on spring $k$ in an elevator accelerating upward at $a$. How do equilibrium extension $x_0$ and oscillation frequency $\\omega$ change?",
        "options": [
            "Both $x_0$ and $\\omega$ increase",
            "$x_0$ increases; $\\omega$ unchanged",
            "$x_0$ unchanged; $\\omega$ increases",
            "Both unchanged",
        ],
        "correct": 1,
        "explanation": "$g_{\\text{eff}} = g + a$ so $kx_0 = m(g+a) \\implies x_0$ increases. But about the new equilibrium, $F = -k\\Delta x$ still, so $\\omega = \\sqrt{k/m}$ is unchanged.",
    },
    {
        "id": "sw-8",
        "topic": "Standing Waves",
        "subtopic": "Superposition",
        "level": 5,
        "type": "numerical",
        "question": "$y_1 = 3.0\\sin(4x - 2t)$ and $y_2 = 3.0\\sin(4x + 2t)$ (SI units) interfere. Find the distance between adjacent nodes in meters.",
        "correct": 0.785,
        "tolerance": 0.015,
        "unit": "m",
        "explanation": "$y = 6.0\\sin(4x)\\cos(2t)$. Nodes: $\\sin(4x)=0 \\implies x = n\\pi/4$. Spacing $= \\pi/4 \\approx 0.785$ m.",
    },
    # ═══════════════════════════════════════
    # DRAWING QUESTIONS
    # ═══════════════════════════════════════
    {
        "id": "draw-1",
        "topic": "Standing Waves",
        "subtopic": "Harmonics",
        "level": 2,
        "type": "drawing",
        "question": "Sketch the 3rd harmonic standing wave for a string fixed at both ends. Label nodes (N) and antinodes (A).",
        "drawing_prompt": "Draw the 3rd harmonic of a string fixed at both ends",
        "eval_criteria": [
            "Shows 3 half-wavelengths in the string",
            "Has 4 nodes (including 2 endpoints)",
            "Has 3 antinodes",
            "Sinusoidal shape",
            "Equal amplitude at each antinode",
        ],
        "explanation": "3rd harmonic: $\\lambda = \\frac{2L}{3}$. There are $n+1 = 4$ nodes and 3 antinodes.",
    },
    {
        "id": "draw-2",
        "topic": "SHM",
        "subtopic": "Energy",
        "level": 3,
        "type": "drawing",
        "question": "Sketch KE and PE vs displacement $x$ (from $-A$ to $+A$) for SHM. Include the total energy line.",
        "drawing_prompt": "Draw KE and PE vs displacement for SHM",
        "eval_criteria": [
            "PE is upward parabola centered at x=0",
            "PE = 0 at x=0, max at x=±A",
            "KE is inverted parabola",
            "KE max at x=0, zero at x=±A",
            "Curves intersect at x = ±A/√2",
            "Horizontal total energy line",
        ],
        "explanation": "$\\text{PE} = \\frac{1}{2}kx^2$ (parabola). $\\text{KE} = \\frac{1}{2}k(A^2 - x^2)$ (inverted parabola). They cross at $x = \\pm A/\\sqrt{2}$.",
    },
    {
        "id": "draw-3",
        "topic": "Standing Waves",
        "subtopic": "Resonance",
        "level": 3,
        "type": "drawing",
        "question": "Sketch the 1st and 3rd harmonics of a pipe closed at the left end and open at the right. Label N and A.",
        "drawing_prompt": "Draw 1st and 3rd harmonics of a closed-open pipe",
        "eval_criteria": [
            "Node at closed (left) end",
            "Antinode at open (right) end",
            "1st harmonic: quarter wavelength fits in pipe",
            "3rd harmonic: three-quarter wavelength fits",
            "Sinusoidal shapes",
        ],
        "explanation": "Closed-open pipe: node at closed end, antinode at open end. 1st: $L = \\lambda/4$. 3rd: $L = 3\\lambda/4$. Only odd harmonics.",
    },
    {
        "id": "draw-4",
        "topic": "Standing Waves",
        "subtopic": "Superposition",
        "level": 4,
        "type": "drawing",
        "question": "Two opposite pulses approach each other. Sketch 3 frames: (1) before, (2) at complete overlap, (3) after passing through.",
        "drawing_prompt": "Draw 3 frames of destructive pulse superposition",
        "eval_criteria": [
            "Frame 1: two separate pulses (one up, one down) approaching",
            "Frame 2: complete destructive interference (flat line)",
            "Frame 3: pulses re-emerge and continue in original directions",
            "Shapes preserved after passing through",
        ],
        "explanation": "At complete overlap: destructive interference gives zero displacement. Pulses pass through each other unchanged — superposition is linear.",
    },
    # ═══════════════════════════════════════
    # MATH INPUT QUESTIONS
    # ═══════════════════════════════════════
    {
        "id": "math-1",
        "topic": "SHM",
        "subtopic": "Equations of Motion",
        "level": 3,
        "type": "math_input",
        "question": "Given $m = 0.5$ kg, $k = 200$ N/m, $A = 0.1$ m, starting at max displacement. Write $x(t)$.",
        "expected_form": "x(t) = 0.1 \\cos(20t)",
        "eval_keywords": ["0.1", "cos", "20"],
        "eval_criteria": [
            "Amplitude is 0.1 m",
            "ω = √(k/m) = 20 rad/s",
            "Uses cosine (starts at max displacement)",
            "x(t) = 0.1 cos(20t)",
        ],
        "explanation": "$x(t) = A\\cos(\\omega t)$ with $\\omega = \\sqrt{k/m} = 20$ rad/s. So $x(t) = 0.1\\cos(20t)$.",
    },
    {
        "id": "math-2",
        "topic": "SHM",
        "subtopic": "Equations of Motion",
        "level": 4,
        "type": "math_input",
        "question": "From $x(t) = A\\cos(\\omega t + \\phi)$, derive $v(t)$ and $a(t)$. Write both expressions.",
        "expected_form": "v(t) = -A\\omega \\sin(\\omega t + \\phi),\\quad a(t) = -A\\omega^2 \\cos(\\omega t + \\phi)",
        "eval_keywords": ["-A", "omega", "sin", "omega^2", "cos", "derivative"],
        "eval_criteria": [
            "v(t) = -Aω sin(ωt + φ)",
            "a(t) = -Aω² cos(ωt + φ)",
            "Correct negative signs",
            "a(t) = -ω²x(t)",
        ],
        "explanation": "$v = \\frac{dx}{dt} = -A\\omega\\sin(\\omega t + \\phi)$. $a = \\frac{dv}{dt} = -A\\omega^2\\cos(\\omega t + \\phi) = -\\omega^2 x$.",
    },
    {
        "id": "math-3",
        "topic": "Standing Waves",
        "subtopic": "Wave Equation",
        "level": 5,
        "type": "math_input",
        "question": "Write $f_n$ for: (a) string of length $L$, tension $T$, density $\\mu$, fixed at both ends; (b) pipe of length $L$, closed at one end, open at the other (sound speed $v$).",
        "expected_form": "f_n = \\frac{n}{2L}\\sqrt{\\frac{T}{\\mu}},\\; n=1,2,3\\ldots \\quad f_n = \\frac{nv}{4L},\\; n=1,3,5\\ldots",
        "eval_keywords": ["n", "2L", "T", "mu", "4L", "odd"],
        "eval_criteria": [
            "String: fₙ = n/(2L)√(T/μ), all n",
            "Pipe: fₙ = nv/(4L), odd n only",
        ],
        "explanation": "String: $f_n = \\frac{n}{2L}\\sqrt{\\frac{T}{\\mu}}$, all $n$. Pipe: $f_n = \\frac{nv}{4L}$, odd $n$ only.",
    },
]
